//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MavAutoKozm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MavAutoKozm.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///A &quot;Megrendelés indítása&quot; gombra kattintva már ki is választhatja az önnek megfelelő kategóriát, majd az igények felmérését követően el is végezzük azokat járművén..
        /// </summary>
        public static string Hogyan_lehet_megrendelni {
            get {
                return ResourceManager.GetString("Hogyan lehet megrendelni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hogyan lehet megrendelni.
        /// </summary>
        public static string Hogyan_lehet_megrendelni_L {
            get {
                return ResourceManager.GetString("Hogyan lehet megrendelni_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamion.
        /// </summary>
        public static string Kamion {
            get {
                return ResourceManager.GetString("Kamion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategória.
        /// </summary>
        public static string Kategória {
            get {
                return ResourceManager.GetString("Kategória", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megrendelés Indítása.
        /// </summary>
        public static string Megrendelés_Indítása {
            get {
                return ResourceManager.GetString("Megrendelés Indítása", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Cégünk gondoskodik mind az elszállításról mind az ügyfélnek átadásról is melyeket telefonon egyezetünk a folyamatok befejeztével..
        /// </summary>
        public static string Mikor_lehet_átvenni {
            get {
                return ResourceManager.GetString("Mikor lehet átvenni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikor lehet átvenni.
        /// </summary>
        public static string Mikor_lehet_átvenni_L {
            get {
                return ResourceManager.GetString("Mikor lehet átvenni_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        public static string Motor {
            get {
                return ResourceManager.GetString("Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cégünk egy új és kényelmesebb módját kínálja szeretett járművének tisztán tartására és megőrzésére az utókornak..
        /// </summary>
        public static string Röviden_a_cégünkről {
            get {
                return ResourceManager.GetString("Röviden a cégünkről", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Röviden a cégünkről.
        /// </summary>
        public static string Röviden_a_cégünkről_L {
            get {
                return ResourceManager.GetString("Röviden a cégünkről_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Személyautó.
        /// </summary>
        public static string Személyautó {
            get {
                return ResourceManager.GetString("Személyautó", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teherautó.
        /// </summary>
        public static string Teherautó {
            get {
                return ResourceManager.GetString("Teherautó", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözöljük.
        /// </summary>
        public static string Üdvözöljük {
            get {
                return ResourceManager.GetString("Üdvözöljük", resourceCulture);
            }
        }
    }
}
