//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MavAutoKozm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MavAutoKozm.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alap.
        /// </summary>
        public static string Alap {
            get {
                return ResourceManager.GetString("Alap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ár.
        /// </summary>
        public static string Ár {
            get {
                return ResourceManager.GetString("Ár", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Bejelentkezés {
            get {
                return ResourceManager.GetString("Bejelentkezés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belső tisztítás.
        /// </summary>
        public static string Belső_tisztítás {
            get {
                return ResourceManager.GetString("Belső tisztítás", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elfelejtettem a jelszavam.
        /// </summary>
        public static string Elfelejtettem_a_jelszavam {
            get {
                return ResourceManager.GetString("Elfelejtettem a jelszavam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-es megerősítés újraküldése.
        /// </summary>
        public static string Email_es_megerősítés_újraküldése {
            get {
                return ResourceManager.GetString("Email-es megerősítés újraküldése", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlékezz rám.
        /// </summary>
        public static string Emlékezz_rám {
            get {
                return ResourceManager.GetString("Emlékezz rám", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó adatai.
        /// </summary>
        public static string Felhasználó_adatai {
            get {
                return ResourceManager.GetString("Felhasználó adatai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználók.
        /// </summary>
        public static string Felhasználók {
            get {
                return ResourceManager.GetString("Felhasználók", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Főoldal.
        /// </summary>
        public static string Főoldal {
            get {
                return ResourceManager.GetString("Főoldal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///A &quot;Megrendelés indítása&quot; gombra kattintva már ki is választhatja az önnek megfelelő kategóriát, majd az igények felmérését követően el is végezzük azokat járművén..
        /// </summary>
        public static string Hogyan_lehet_megrendelni {
            get {
                return ResourceManager.GetString("Hogyan lehet megrendelni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hogyan lehet megrendelni.
        /// </summary>
        public static string Hogyan_lehet_megrendelni_L {
            get {
                return ResourceManager.GetString("Hogyan lehet megrendelni_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igények.
        /// </summary>
        public static string Igények {
            get {
                return ResourceManager.GetString("Igények", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Járműveim.
        /// </summary>
        public static string Járműveim {
            get {
                return ResourceManager.GetString("Járműveim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Járművek.
        /// </summary>
        public static string Járművek {
            get {
                return ResourceManager.GetString("Járművek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        public static string Jelszó {
            get {
                return ResourceManager.GetString("Jelszó", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó megerősítés.
        /// </summary>
        public static string Jelszó_megerősítés {
            get {
                return ResourceManager.GetString("Jelszó megerősítés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamion.
        /// </summary>
        public static string Kamion {
            get {
                return ResourceManager.GetString("Kamion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategória.
        /// </summary>
        public static string Kategória {
            get {
                return ResourceManager.GetString("Kategória", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kavics védő fólia.
        /// </summary>
        public static string Kavics_védő_fólia {
            get {
                return ResourceManager.GetString("Kavics védő fólia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerámia bevonat.
        /// </summary>
        public static string Kerámia_bevonat {
            get {
                return ResourceManager.GetString("Kerámia bevonat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresztnév.
        /// </summary>
        public static string Keresztnév {
            get {
                return ResourceManager.GetString("Keresztnév", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Köszönjük a megrendelést.
        /// </summary>
        public static string Köszönjük_a_megrendelést {
            get {
                return ResourceManager.GetString("Köszönjük a megrendelést", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Külső tisztítás.
        /// </summary>
        public static string Külső_tisztítás {
            get {
                return ResourceManager.GetString("Külső tisztítás", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legjobb választás.
        /// </summary>
        public static string Legjobb_választás {
            get {
                return ResourceManager.GetString("Legjobb választás", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Márka.
        /// </summary>
        public static string Márka {
            get {
                return ResourceManager.GetString("Márka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megrendelés.
        /// </summary>
        public static string Megrendelés {
            get {
                return ResourceManager.GetString("Megrendelés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megrendelés Indítása.
        /// </summary>
        public static string Megrendelés_Indítása {
            get {
                return ResourceManager.GetString("Megrendelés Indítása", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megrendeléseim.
        /// </summary>
        public static string Megrendeléseim {
            get {
                return ResourceManager.GetString("Megrendeléseim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megrendelések.
        /// </summary>
        public static string Megrendelések {
            get {
                return ResourceManager.GetString("Megrendelések", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megrendelési azonosítója.
        /// </summary>
        public static string Megrendelési_azonosítója {
            get {
                return ResourceManager.GetString("Megrendelési azonosítója", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megrendelési idő.
        /// </summary>
        public static string Megrendelési_idő {
            get {
                return ResourceManager.GetString("Megrendelési idő", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melyik járművét választja ki?.
        /// </summary>
        public static string Melyik_járművét_választja_ki_ {
            get {
                return ResourceManager.GetString("Melyik járművét választja ki?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Cégünk gondoskodik mind az elszállításról mind az ügyfélnek átadásról is melyeket telefonon egyezetünk a folyamatok befejeztével..
        /// </summary>
        public static string Mikor_lehet_átvenni {
            get {
                return ResourceManager.GetString("Mikor lehet átvenni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikor lehet átvenni.
        /// </summary>
        public static string Mikor_lehet_átvenni_L {
            get {
                return ResourceManager.GetString("Mikor lehet átvenni_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minőségi szint.
        /// </summary>
        public static string Minőségi_szint {
            get {
                return ResourceManager.GetString("Minőségi szint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modell.
        /// </summary>
        public static string Modell {
            get {
                return ResourceManager.GetString("Modell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módosítás.
        /// </summary>
        public static string Módosítás {
            get {
                return ResourceManager.GetString("Módosítás", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        public static string Motor {
            get {
                return ResourceManager.GetString("Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Összegzés.
        /// </summary>
        public static string Összegzés {
            get {
                return ResourceManager.GetString("Összegzés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polírozás.
        /// </summary>
        public static string Polírozás {
            get {
                return ResourceManager.GetString("Polírozás", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prémium.
        /// </summary>
        public static string Prémium {
            get {
                return ResourceManager.GetString("Prémium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztráció.
        /// </summary>
        public static string Regisztráció {
            get {
                return ResourceManager.GetString("Regisztráció", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendszám.
        /// </summary>
        public static string Rendszám {
            get {
                return ResourceManager.GetString("Rendszám", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Részletek.
        /// </summary>
        public static string Részletek {
            get {
                return ResourceManager.GetString("Részletek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cégünk egy új és kényelmesebb módját kínálja szeretett járművének tisztán tartására és megőrzésére az utókornak..
        /// </summary>
        public static string Röviden_a_cégünkről {
            get {
                return ResourceManager.GetString("Röviden a cégünkről", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Röviden a cégünkről.
        /// </summary>
        public static string Röviden_a_cégünkről_L {
            get {
                return ResourceManager.GetString("Röviden a cégünkről_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Személyautó.
        /// </summary>
        public static string Személyautó {
            get {
                return ResourceManager.GetString("Személyautó", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szín.
        /// </summary>
        public static string Szín {
            get {
                return ResourceManager.GetString("Szín", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teherautó.
        /// </summary>
        public static string Teherautó {
            get {
                return ResourceManager.GetString("Teherautó", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonszám.
        /// </summary>
        public static string Telefonszám {
            get {
                return ResourceManager.GetString("Telefonszám", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        public static string Törlés {
            get {
                return ResourceManager.GetString("Törlés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tovább.
        /// </summary>
        public static string Tovább {
            get {
                return ResourceManager.GetString("Tovább", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözöljük.
        /// </summary>
        public static string Üdvözöljük {
            get {
                return ResourceManager.GetString("Üdvözöljük", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Végrehajtási idő.
        /// </summary>
        public static string Végrehajtási_idő {
            get {
                return ResourceManager.GetString("Végrehajtási idő", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vezetéknév.
        /// </summary>
        public static string Vezetéknév {
            get {
                return ResourceManager.GetString("Vezetéknév", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waxolás.
        /// </summary>
        public static string Waxolás {
            get {
                return ResourceManager.GetString("Waxolás", resourceCulture);
            }
        }
    }
}
